window.CONFUSABLE_WORD_PAIRS = [
  { words: ["collision", "collusion"], distinction: "collision 是物体或观点的碰撞；collusion 是为了欺骗而秘密串通。", hook: "撞上了是 collision；偷偷站到同一边是 collusion。" },
  { words: ["disparage", "disparate"], distinction: "disparage 是贬低、轻视；disparate 是彼此迥异、难以归为一类。", hook: "-parage 指评价变低；-parate 联想到 separate，彼此不同。" },
  { words: ["prescribe", "proscribe"], distinction: "prescribe 是开药或规定应该做什么；proscribe 是正式禁止。", hook: "pre- 写在前面供你照做；pro- 在这里是宣布禁令。" },
  { words: ["arrogate", "abrogate"], distinction: "arrogate 是擅自夺取权利；abrogate 是正式废除法律或协议。", hook: "arrogate 把权力拿到自己身上；abrogate 把规则撤掉。" },
  { words: ["contrive", "contrite"], distinction: "contrive 是设法做成或精心设计；contrite 是因过错而真诚悔恨。", hook: "contrive 里有行动；contrite 里有悔意。" },
  { words: ["flagrant", "fragrant"], distinction: "flagrant 是公然恶劣、令人震惊；fragrant 是芳香的。", hook: "flagrant 的 l 像警灯；fragrant 的 r 联想到 rose。" },
  { words: ["indolent", "insolent"], distinction: "indolent 是懒散、不愿努力；insolent 是傲慢无礼。", hook: "drowsy 的 d 帮你记 indolent；insult 帮你记 insolent。" },
  { words: ["vigorous", "rigorous"], distinction: "vigorous 强调有活力、有力量；rigorous 强调严格、缜密。", hook: "vigor 是能量；rigor 是严谨。" },
  { words: ["flutter", "flatter"], distinction: "flutter 是快速拍动或颤动；flatter 是奉承。", hook: "蝴蝶 flutter；甜言蜜语 flatter。" },
  { words: ["fortify", "mortify"], distinction: "fortify 是加固或增强；mortify 是使羞愧、窘迫。", hook: "fort 像堡垒，所以 fortify 是加强；mort 像被羞得想钻地。" },
  { words: ["pigment", "figment"], distinction: "pigment 是真实的色素；figment 是凭空想象的事物。", hook: "pigment 能涂在纸上；figment 只存在于想象中。" },
  { words: ["demure", "demur"], distinction: "demure 是端庄矜持的；demur 是表示异议或犹豫反对。", hook: "有 e 的 demure 是形容词；短一点的 demur 是提出反对。" },
  { words: ["impervious", "imperious"], distinction: "impervious 是不能穿透或不受影响；imperious 是专横傲慢、命令式的。", hook: "impervious 里有 v，像防护屏障；imperious 像 emperor 在发号施令。" },
  { words: ["liable", "viable"], distinction: "liable 是可能发生或负有法律责任；viable 是能够成功、存活或实行。", hook: "liable 常接 to；viable 是方案能活下去。" },
  { words: ["pamper", "tamper"], distinction: "pamper 是娇惯、纵容；tamper 是擅自改动或干预。", hook: "pamper a child；tamper with evidence。" },
  { words: ["potent", "patent"], distinction: "potent 是强有力、效力强；patent 是明显的，或指专利。", hook: "potent power；patent protection。" },
  { words: ["reverie", "revere"], distinction: "reverie 是白日梦、遐想；revere 是尊敬、崇敬。", hook: "沉入 reverie；抬头 revere。" },
  { words: ["defer", "deter"], distinction: "defer 是推迟或听从；deter 是威慑、阻止。", hook: "defer 把时间往后放；deter 把人挡在行动之前。" },
  { words: ["forgo", "forge"], distinction: "forgo 是主动放弃；forge 是锻造或伪造。", hook: "forgo = go without；forge = 在炉火中打造。" },
  { words: ["lurid", "lucid"], distinction: "lurid 是骇人听闻或俗艳的；lucid 是清晰易懂、神志清醒的。", hook: "lurid 让人不适；lucid 让人看清。" },
  { words: ["mediate", "meditate"], distinction: "mediate 是在双方之间调解；meditate 是独自沉思或冥想。", hook: "mediate 处理两边；meditate 面对内心。" },
  { words: ["repeal", "repel"], distinction: "repeal 是废除法律；repel 是击退或使厌恶。", hook: "repeal a law；repel an attack。" },
  { words: ["scant", "slant"], distinction: "scant 是不足、很少；slant 是倾斜或带有偏向。", hook: "scant quantity；slant angle。" },
  { words: ["shear", "sheer"], distinction: "shear 是剪切；sheer 是完全的、陡峭的或透明轻薄的。", hook: "shear sheep；sheer luck。" },
  { words: ["taunt", "taint"], distinction: "taunt 是嘲弄、奚落；taint 是污染、玷污。", hook: "taunt 伤人；taint 伤品质。" },
  { words: ["yield", "wield"], distinction: "yield 是产生、让步；wield 是挥舞或运用权力。", hook: "yield results；wield influence。" },
  { words: ["amicable", "amiable"], distinction: "amicable 多形容关系或解决方式友好；amiable 多形容人亲切友善。", hook: "amicable agreement；amiable person。" },
  { words: ["imprudent", "impudent"], distinction: "imprudent 是不明智、轻率；impudent 是无礼、放肆。", hook: "prudence 对应明智；impudence 对应无礼。" },
  { words: ["sober", "somber"], distinction: "sober 是清醒、未醉或严肃冷静；somber 是阴沉、忧郁。", hook: "sober mind；somber mood。" },
  { words: ["delude", "elude"], distinction: "delude 是欺骗、使产生错觉；elude 是逃避、使无法达到。", hook: "delude someone；elude capture。" },
  { words: ["degradation", "depredation"], distinction: "degradation 是贬低、退化；depredation 是劫掠和破坏。", hook: "grade 降低是 degradation；predator 掠夺是 depredation。" },
  { words: ["prosecution", "persecution"], distinction: "prosecution 是依法起诉；persecution 是持续迫害。", hook: "prosecutor 在法庭；persecutor 在压迫别人。" },
  { words: ["complacent", "complement"], distinction: "complacent 是自满；complement 是补足、相得益彰。", hook: "complacent 对自己太满意；complement 让整体更完整。" },
  { words: ["aesthetic", "apathetic"], distinction: "aesthetic 与审美有关；apathetic 是冷漠、缺乏兴趣。", hook: "aesthetic cares about beauty；apathetic does not care。" },
  { words: ["denigrate", "designate"], distinction: "denigrate 是贬低、诋毁；designate 是指定、命名。", hook: "denigrate lowers a reputation；designate gives a label。" },
  { words: ["extricate", "intricate"], distinction: "extricate 是使摆脱困境；intricate 是错综复杂的。", hook: "ex- 向外脱身；in- 像深入复杂结构。" },
  { words: ["oscillate", "vacillate"], distinction: "oscillate 可指物理摆动或观点来回变化；vacillate 专指犹豫不决。", hook: "钟摆 oscillates；拿不定主意时 vacillate。" },
  { words: ["plaintive", "plaintiff"], distinction: "plaintive 是声音哀伤的；plaintiff 是法庭上的原告。", hook: "plaintive cry；plaintiff files a claim。" },
  { words: ["specious", "spurious"], distinction: "specious 是表面有理但实际错误；spurious 是虚假、伪造或来源不正。", hook: "specious argument 看似合理；spurious evidence 根本不真。" },
  { words: ["discreet", "discrete"], distinction: "discreet 是谨慎低调；discrete 是分离、互不相连。", hook: "discrete 的两个 e 被分开；discreet 的 ee 靠在一起守秘密。" },
  { words: ["censure", "censor"], distinction: "censure 是公开谴责；censor 是审查或删改内容。", hook: "censure expresses blame；censor removes content。" },
  { words: ["anecdote", "antidote"], distinction: "anecdote 是轶事；antidote 是解毒剂或补救方法。", hook: "anecdote tells a story；antidote treats a poison。" },
  { words: ["callous", "callow"], distinction: "callous 是冷酷无情；callow 是年轻且缺乏经验。", hook: "callous heart；callow youth。" },
  { words: ["commend", "commence"], distinction: "commend 是称赞、推荐；commence 是开始。", hook: "commend a student；commence a ceremony。" },
  { words: ["vivacious", "voracious"], distinction: "vivacious 是活泼有生气；voracious 是贪吃或极度渴求。", hook: "vivacious vitality；voracious appetite。" },
  { words: ["brood", "brook"], distinction: "brood 可指一窝幼崽，也可指闷闷不乐地反复思量；brook 是小溪，作动词还可表示容忍。", hook: "brood over a problem；a babbling brook。" },
  { words: ["clasp", "clash"], distinction: "clasp 是紧握、扣住；clash 是发生冲突或不协调。", hook: "clasp hands；clash with an opponent。" },
  { words: ["crave", "craven"], distinction: "crave 是强烈渴望；craven 是怯懦的、缺乏勇气的。", hook: "crave 多出的 n 让渴望的人变成退缩的 craven coward。" },
  { words: ["graze", "grave"], distinction: "graze 是吃草或轻轻擦过；grave 是坟墓，也可表示严肃或严重。", hook: "cattle graze；a grave warning。" },
  { words: ["heave", "weave"], distinction: "heave 是用力举起、拖动或喘息；weave 是编织或穿行。", hook: "heave a box；weave a basket。" },
  { words: ["revel", "repel"], distinction: "revel 是狂欢或陶醉其中；repel 是击退、排斥或使厌恶。", hook: "revel in success；repel an attack。" },
  { words: ["shave", "shove"], distinction: "shave 是剃毛或削去薄层；shove 是猛推、用力塞入。", hook: "shave a beard；shove the door。" },
  { words: ["sheer", "sneer"], distinction: "sheer 是完全的、陡峭的或轻薄透明的；sneer 是冷笑、讥讽。", hook: "sheer luck；sneer at an idea。" },
  { words: ["tread", "dread"], distinction: "tread 是踩、行走；dread 是恐惧或畏惧。", hook: "tread carefully；dread the result。" },
  { words: ["comely", "homely"], distinction: "comely 表示相貌秀丽；homely 表示朴实如家，在美式英语中也可指相貌平平。", hook: "comely appearance；homely comfort。" },
  { words: ["deduce", "seduce"], distinction: "deduce 是根据证据推断；seduce 是诱惑、引诱。", hook: "deduce a conclusion；seduce someone with promises。" },
  { words: ["forage", "forge"], distinction: "forage 是搜寻食物或物资；forge 是锻造、建立，也可指伪造。", hook: "forage for food；forge a signature。" },
  { words: ["menial", "genial"], distinction: "menial 是地位低、技术含量低的；genial 是亲切友好的、令人愉快的。", hook: "menial work；a genial host。" },
  { words: ["outlay", "outlaw"], distinction: "outlay 是一笔支出；outlaw 是亡命徒，作动词表示宣布非法。", hook: "capital outlay；outlaw a practice。" },
  { words: ["pamper", "hamper"], distinction: "pamper 是娇惯、纵容；hamper 是妨碍，也可指有盖的大篮子。", hook: "pamper a child；hamper progress。" },
  { words: ["reign", "resign"], distinction: "reign 是统治、占主导；resign 是辞职或听任。", hook: "a king reigns；an official resigns。" },
  { words: ["strain", "stain"], distinction: "strain 是拉紧、压力或过度使用；stain 是染色、污点。", hook: "muscle strain；ink stain。" },
  { words: ["temper", "tamper"], distinction: "temper 是脾气，也可表示调和、缓和；tamper 是擅自干预或篡改。", hook: "control a temper；tamper with evidence。" },
  { words: ["wither", "hither"], distinction: "wither 是枯萎、衰退；hither 是到这里、向此处。", hook: "flowers wither；come hither。" },
  { words: ["gratify", "ratify"], distinction: "gratify 是使满意、满足；ratify 是正式批准协议或决定。", hook: "gratify a desire；ratify a treaty。" },
  { words: ["lumber", "slumber"], distinction: "lumber 是木材，也可指笨重地移动；slumber 是睡眠、沉睡。", hook: "lumber yard；deep slumber。" },
  { words: ["pliable", "liable"], distinction: "pliable 是柔韧、易弯或易受影响；liable 是可能发生或负有责任。", hook: "pliable material；liable for damages。" },
  { words: ["potent", "portent"], distinction: "potent 是强有力、效力强；portent 是预兆，尤指重大事件的征兆。", hook: "potent medicine；a portent of change。" },
  { words: ["shatter", "scatter"], distinction: "shatter 是打碎或彻底破坏；scatter 是使分散、撒开。", hook: "shatter glass；scatter seeds。" },
  { words: ["wither", "whither"], distinction: "wither 是枯萎；whither 是往哪里、走向何种结果。", hook: "plants wither；whither are we going?" },
  { words: ["denounce", "renounce"], distinction: "denounce 是公开谴责或告发；renounce 是正式放弃权利、信仰或关系。", hook: "denounce corruption；renounce a claim。" },
  { words: ["material", "maternal"], distinction: "material 是材料、物质或重要相关的；maternal 是母亲的、母系的。", hook: "material evidence；maternal care。" },
  { words: ["penchant", "enchant"], distinction: "penchant 是强烈爱好、偏好；enchant 是使着迷或施魔法。", hook: "a penchant for art；enchant an audience。" },
  { words: ["platitude", "latitude"], distinction: "platitude 是陈词滥调；latitude 是纬度，也表示行动自由或余地。", hook: "repeat a platitude；give someone latitude。" },
  { words: ["allay", "array"], distinction: "allay 是减轻恐惧、怀疑或担忧；array 是排列、陈列，也可指一大批。", hook: "allay fears；an array of options。" },
  { words: ["ardor", "adorn"], distinction: "ardor 是热情、激情；adorn 是装饰、使增色。", hook: "revolutionary ardor；adorn a room。" },
  { words: ["axiom", "maxim"], distinction: "axiom 是被视为不证自明的原理；maxim 是指导行为的格言或准则。", hook: "a mathematical axiom；a moral maxim。" },
  { words: ["beget", "bigot"], distinction: "beget 是生育、导致或产生；bigot 是固执偏见者。", hook: "violence begets violence；a narrow-minded bigot。" },
  { words: ["bluff", "blunt"], distinction: "bluff 是虚张声势，也可指直率或悬崖；blunt 是钝的、直言不讳的。", hook: "call a bluff；a blunt remark。" },
  { words: ["bogus", "locus"], distinction: "bogus 是假的、伪造的；locus 是地点、中心或数学中的轨迹。", hook: "a bogus claim；the locus of control。" },
  { words: ["brink", "brook"], distinction: "brink 是边缘或紧要关头；brook 是小溪，作动词表示容忍。", hook: "on the brink；cross a brook。" },
  { words: ["brood", "breed"], distinction: "brood 是一窝幼崽或沉思烦恼；breed 是繁殖、培育，也可指品种。", hook: "brood over failure；breed cattle。" },
  { words: ["chord", "hoard"], distinction: "chord 是和弦或心弦；hoard 是大量囤积，也指贮藏物。", hook: "strike a chord；hoard supplies。" },
  { words: ["dogma", "magma"], distinction: "dogma 是不容质疑的教条；magma 是地下熔融岩浆。", hook: "religious dogma；volcanic magma。" },
  { words: ["drift", "graft"], distinction: "drift 是漂流、逐渐变化或大意；graft 是嫁接、移植，也可指贪腐。", hook: "drift away；skin graft。" },
  { words: ["erect", "enact"], distinction: "erect 是竖立、建造或直立的；enact 是制定法律或把情节演出来。", hook: "erect a monument；enact a law。" },
  { words: ["evade", "elude"], distinction: "evade 强调主动逃避责任、问题或追捕；elude 强调成功逃脱，或让人难以理解、获得。", hook: "evade a question；the answer eludes me。" },
  { words: ["flock", "cloak"], distinction: "flock 是鸟群、羊群或成群聚集；cloak 是斗篷，也可表示掩盖。", hook: "a flock of birds；cloak the truth。" },
  { words: ["lurid", "acrid"], distinction: "lurid 是骇人听闻或颜色俗艳；acrid 是气味、味道或言辞辛辣刺鼻。", hook: "lurid headlines；acrid smoke。" },
  { words: ["murky", "surly"], distinction: "murky 是昏暗、浑浊或含糊不清；surly 是阴沉粗暴、脾气不佳。", hook: "murky water；a surly reply。" },
  { words: ["parry", "array"], distinction: "parry 是挡开攻击或巧妙回避问题；array 是排列、部署或一大批。", hook: "parry a blow；array the evidence。" },
  { words: ["revel", "rival"], distinction: "revel 是狂欢、陶醉；rival 是竞争对手，也可表示与之匹敌。", hook: "revel in praise；rival a champion。" },
  { words: ["scant", "stint"], distinction: "scant 是数量不足、勉强达到；stint 是一段任期或限定供应。", hook: "scant evidence；a brief stint abroad。" },
  { words: ["stain", "taint"], distinction: "stain 多指可见污渍或染色；taint 更强调污染品质、名誉或纯洁性。", hook: "stain a shirt；taint a reputation。" },
  { words: ["stoic", "stock"], distinction: "stoic 是坚忍克制的人或斯多葛式的；stock 是库存、股份或家畜。", hook: "remain stoic；check the stock。" },
  { words: ["weary", "chary"], distinction: "weary 是疲倦或厌烦；chary 是谨慎、不愿冒险。", hook: "weary travelers；chary of promises。" },
  { words: ["acute", "astute"], distinction: "acute 是尖锐、剧烈、敏锐或急性的；astute 是精明、判断敏锐。", hook: "acute pain；an astute observer。" },
  { words: ["ardor", "candor"], distinction: "ardor 是热烈激情；candor 是坦率、直言不讳。", hook: "speak with ardor；answer with candor。" },
  { words: ["attire", "satire"], distinction: "attire 是服装、穿着；satire 是用讽刺手法批评的作品。", hook: "formal attire；political satire。" },
  { words: ["banish", "garish"], distinction: "banish 是驱逐、消除；garish 是颜色或装饰过分鲜艳俗气。", hook: "banish a thought；garish colors。" },
  { words: ["brash", "broach"], distinction: "brash 是鲁莽自负或刺眼的；broach 是首次提出敏感话题，也可指钻开。", hook: "a brash newcomer；broach the subject。" },
  { words: ["canard", "candid"], distinction: "canard 是虚假报道或无根据谣言；candid 是坦率真实的。", hook: "spread a canard；give a candid answer。" },
  { words: ["candor", "censor"], distinction: "candor 是坦率；censor 是审查、删改内容的人或行为。", hook: "candor reveals；a censor conceals。" },
  { words: ["censor", "census"], distinction: "censor 是审查或删改；census 是人口普查、统计调查。", hook: "censor a film；conduct a census。" },
  { words: ["coerce", "coarse"], distinction: "coerce 是胁迫某人做事；coarse 是粗糙、粗俗或颗粒大的。", hook: "coerce a witness；coarse fabric。" },
  { words: ["cogent", "potent"], distinction: "cogent 强调论证有说服力；potent 强调力量或效力强。", hook: "a cogent argument；a potent drug。" },
  { words: ["confer", "concur"], distinction: "confer 是商议或授予；concur 是同意，或同时发生。", hook: "confer with colleagues；concur with a conclusion。" },
  { words: ["craven", "brazen"], distinction: "craven 是怯懦畏缩；brazen 是厚颜无耻、公然大胆。", hook: "craven fear retreats；brazen conduct pushes forward。" },
  { words: ["dawdle", "dabble"], distinction: "dawdle 是磨蹭、浪费时间；dabble 是浅尝辄止地涉猎。", hook: "dawdle on the way；dabble in painting。" },
  { words: ["decry", "decree"], distinction: "decry 是公开谴责；decree 是权威发布的法令或裁定。", hook: "decry injustice；issue a decree。" },
  { words: ["deduce", "delude"], distinction: "deduce 是推断出真相；delude 是欺骗，使人相信不真实的事。", hook: "deduce from evidence；delude oneself。" },
  { words: ["demise", "debase"], distinction: "demise 是死亡、终止；debase 是降低价值、品质或尊严。", hook: "the demise of a system；debase the currency。" },
  { words: ["demure", "immure"], distinction: "demure 是端庄矜持的；immure 是监禁、禁闭。", hook: "a demure smile；immure someone in a cell。" },
  { words: ["dilute", "delude"], distinction: "dilute 是加水稀释或削弱；delude 是欺骗、使产生错觉。", hook: "dilute a solution；delude an audience。" },
  { words: ["escort", "exhort"], distinction: "escort 是护送、陪同；exhort 是郑重敦促、规劝。", hook: "escort a visitor；exhort voters to act。" },
  { words: ["exempt", "tempt"], distinction: "exempt 是免除义务或不受规则约束；tempt 是诱惑、引诱。", hook: "exempt from tax；tempt someone with a reward。" },
  { words: ["exert", "exhort"], distinction: "exert 是施加力量、影响或努力；exhort 是用言语极力敦促。", hook: "exert pressure；exhort the team。" },
  { words: ["fetter", "deter"], distinction: "fetter 是用镣铐束缚或限制；deter 是通过威慑阻止行动。", hook: "fetter innovation；deter crime。" },
  { words: ["foible", "fable"], distinction: "foible 是无伤大雅的小缺点；fable 是寓言或虚构故事。", hook: "a personal foible；Aesop's fable。" },
  { words: ["forage", "forgo"], distinction: "forage 是搜寻食物或资源；forgo 是自愿放弃。", hook: "forage for supplies；forgo an opportunity。" },
  { words: ["gloomy", "glossy"], distinction: "gloomy 是阴暗、忧郁；glossy 是光亮平滑或包装精美的。", hook: "a gloomy forecast；a glossy magazine。" },
  { words: ["glossy", "gross"], distinction: "glossy 是有光泽、精美包装的；gross 是总的、严重的，也可表示粗俗恶心。", hook: "glossy surface；gross misconduct。" },
  { words: ["hybrid", "hubris"], distinction: "hybrid 是混合物、杂交种；hubris 是导致失败的傲慢自大。", hook: "a hybrid vehicle；tragic hubris。" },
  { words: ["immure", "imbue"], distinction: "immure 是把人禁闭起来；imbue 是使充满某种品质、思想或感情。", hook: "immure behind walls；imbue a text with irony。" },
  { words: ["ambiguous", "ambivalent"], distinction: "ambiguous 指表达或证据有多种解释；ambivalent 指一个人同时抱有相互矛盾的感情。", hook: "ambiguous wording；ambivalent feelings。" },
  { words: ["allay", "alleviate"], distinction: "allay 常搭配 fear、suspicion、concern，强调平息；alleviate 常搭配 pain、poverty、problem，强调缓解负担。", hook: "allay anxiety；alleviate suffering。" },
  { words: ["exasperate", "exacerbate"], distinction: "exasperate 是使某人恼怒；exacerbate 是使问题、病情或矛盾恶化。", hook: "exasperate a teacher；exacerbate a crisis。" },
  { words: ["complaisant", "complacent"], distinction: "complaisant 是殷勤顺从、急于讨好；complacent 是自满、安于现状。", hook: "complaisant toward others；complacent about oneself。" },
  { words: ["propitiate", "propagate"], distinction: "propitiate 是安抚、讨好以消除怒气；propagate 是繁殖或传播思想、信息。", hook: "propitiate critics；propagate a belief。" },
  { words: ["reticent", "laconic"], distinction: "reticent 强调不愿开口或透露信息；laconic 强调说话简短、用词极少。", hook: "reticent because unwilling；laconic because brief。" },
  { words: ["exonerate", "excoriate"], distinction: "exonerate 是证明无罪、免除责任；excoriate 是严厉批评，也可指擦伤皮肤。", hook: "exonerate a suspect；excoriate a policy。" },
  { words: ["garrulous", "gratuitous"], distinction: "garrulous 是过分健谈、喋喋不休；gratuitous 是无缘无故或不必要的，也可表示免费的。", hook: "a garrulous speaker；gratuitous violence。" },
  { words: ["veracious", "voracious"], distinction: "veracious 是诚实、真实准确；voracious 是贪吃或对知识极度渴求。", hook: "veracious = true；voracious = hungry。" },
  { words: ["munificent", "magnanimous"], distinction: "munificent 强调在金钱、礼物上的极度慷慨；magnanimous 强调宽宏大量，尤其是对对手不计前嫌。", hook: "munificent donation；magnanimous in victory。" },
  { words: ["inimical", "insidious"], distinction: "inimical 是公开敌对或有害；insidious 是影响缓慢、隐蔽却危险。", hook: "inimical forces oppose；insidious harm hides。" },
  { words: ["inveterate", "obdurate"], distinction: "inveterate 形容习惯或状态根深蒂固；obdurate 形容人顽固、不肯改变。", hook: "an inveterate habit；an obdurate opponent。" }
];
