window.CONFUSABLE_WORD_PAIRS = [
  { words: ["collision", "collusion"], distinction: "collision 是物体或观点的碰撞；collusion 是为了欺骗而秘密串通。", hook: "撞上了是 collision；偷偷站到同一边是 collusion。" },
  { words: ["disparage", "disparate"], distinction: "disparage 是贬低、轻视；disparate 是彼此迥异、难以归为一类。", hook: "-parage 指评价变低；-parate 联想到 separate，彼此不同。" },
  { words: ["prescribe", "proscribe"], distinction: "prescribe 是开药或规定应该做什么；proscribe 是正式禁止。", hook: "pre- 写在前面供你照做；pro- 在这里是宣布禁令。" },
  { words: ["arrogate", "abrogate"], distinction: "arrogate 是擅自夺取权利；abrogate 是正式废除法律或协议。", hook: "arrogate 把权力拿到自己身上；abrogate 把规则撤掉。" },
  { words: ["contrive", "contrite"], distinction: "contrive 是设法做成或精心设计；contrite 是因过错而真诚悔恨。", hook: "contrive 里有行动；contrite 里有悔意。" },
  { words: ["flagrant", "fragrant"], distinction: "flagrant 是公然恶劣、令人震惊；fragrant 是芳香的。", hook: "flagrant 的 l 像警灯；fragrant 的 r 联想到 rose。" },
  { words: ["indolent", "insolent"], distinction: "indolent 是懒散、不愿努力；insolent 是傲慢无礼。", hook: "drowsy 的 d 帮你记 indolent；insult 帮你记 insolent。" },
  { words: ["vigorous", "rigorous"], distinction: "vigorous 强调有活力、有力量；rigorous 强调严格、缜密。", hook: "vigor 是能量；rigor 是严谨。" },
  { words: ["flutter", "flatter"], distinction: "flutter 是快速拍动或颤动；flatter 是奉承。", hook: "蝴蝶 flutter；甜言蜜语 flatter。" },
  { words: ["fortify", "mortify"], distinction: "fortify 是加固或增强；mortify 是使羞愧、窘迫。", hook: "fort 像堡垒，所以 fortify 是加强；mort 像被羞得想钻地。" },
  { words: ["pigment", "figment"], distinction: "pigment 是真实的色素；figment 是凭空想象的事物。", hook: "pigment 能涂在纸上；figment 只存在于想象中。" },
  { words: ["demure", "demur"], distinction: "demure 是端庄矜持的；demur 是表示异议或犹豫反对。", hook: "有 e 的 demure 是形容词；短一点的 demur 是提出反对。" },
  { words: ["impervious", "imperious"], distinction: "impervious 是不能穿透或不受影响；imperious 是专横傲慢、命令式的。", hook: "impervious 里有 v，像防护屏障；imperious 像 emperor 在发号施令。" },
  { words: ["liable", "viable"], distinction: "liable 是可能发生或负有法律责任；viable 是能够成功、存活或实行。", hook: "liable 常接 to；viable 是方案能活下去。" },
  { words: ["pamper", "tamper"], distinction: "pamper 是娇惯、纵容；tamper 是擅自改动或干预。", hook: "pamper a child；tamper with evidence。" },
  { words: ["potent", "patent"], distinction: "potent 是强有力、效力强；patent 是明显的，或指专利。", hook: "potent power；patent protection。" },
  { words: ["reverie", "revere"], distinction: "reverie 是白日梦、遐想；revere 是尊敬、崇敬。", hook: "沉入 reverie；抬头 revere。" },
  { words: ["defer", "deter"], distinction: "defer 是推迟或听从；deter 是威慑、阻止。", hook: "defer 把时间往后放；deter 把人挡在行动之前。" },
  { words: ["forgo", "forge"], distinction: "forgo 是主动放弃；forge 是锻造或伪造。", hook: "forgo = go without；forge = 在炉火中打造。" },
  { words: ["lurid", "lucid"], distinction: "lurid 是骇人听闻或俗艳的；lucid 是清晰易懂、神志清醒的。", hook: "lurid 让人不适；lucid 让人看清。" },
  { words: ["mediate", "meditate"], distinction: "mediate 是在双方之间调解；meditate 是独自沉思或冥想。", hook: "mediate 处理两边；meditate 面对内心。" },
  { words: ["repeal", "repel"], distinction: "repeal 是废除法律；repel 是击退或使厌恶。", hook: "repeal a law；repel an attack。" },
  { words: ["scant", "slant"], distinction: "scant 是不足、很少；slant 是倾斜或带有偏向。", hook: "scant quantity；slant angle。" },
  { words: ["shear", "sheer"], distinction: "shear 是剪切；sheer 是完全的、陡峭的或透明轻薄的。", hook: "shear sheep；sheer luck。" },
  { words: ["taunt", "taint"], distinction: "taunt 是嘲弄、奚落；taint 是污染、玷污。", hook: "taunt 伤人；taint 伤品质。" },
  { words: ["yield", "wield"], distinction: "yield 是产生、让步；wield 是挥舞或运用权力。", hook: "yield results；wield influence。" },
  { words: ["amicable", "amiable"], distinction: "amicable 多形容关系或解决方式友好；amiable 多形容人亲切友善。", hook: "amicable agreement；amiable person。" },
  { words: ["imprudent", "impudent"], distinction: "imprudent 是不明智、轻率；impudent 是无礼、放肆。", hook: "prudence 对应明智；impudence 对应无礼。" },
  { words: ["sober", "somber"], distinction: "sober 是清醒、未醉或严肃冷静；somber 是阴沉、忧郁。", hook: "sober mind；somber mood。" },
  { words: ["delude", "elude"], distinction: "delude 是欺骗、使产生错觉；elude 是逃避、使无法达到。", hook: "delude someone；elude capture。" },
  { words: ["degradation", "depredation"], distinction: "degradation 是贬低、退化；depredation 是劫掠和破坏。", hook: "grade 降低是 degradation；predator 掠夺是 depredation。" },
  { words: ["prosecution", "persecution"], distinction: "prosecution 是依法起诉；persecution 是持续迫害。", hook: "prosecutor 在法庭；persecutor 在压迫别人。" },
  { words: ["complacent", "complement"], distinction: "complacent 是自满；complement 是补足、相得益彰。", hook: "complacent 对自己太满意；complement 让整体更完整。" },
  { words: ["aesthetic", "apathetic"], distinction: "aesthetic 与审美有关；apathetic 是冷漠、缺乏兴趣。", hook: "aesthetic cares about beauty；apathetic does not care。" },
  { words: ["denigrate", "designate"], distinction: "denigrate 是贬低、诋毁；designate 是指定、命名。", hook: "denigrate lowers a reputation；designate gives a label。" },
  { words: ["extricate", "intricate"], distinction: "extricate 是使摆脱困境；intricate 是错综复杂的。", hook: "ex- 向外脱身；in- 像深入复杂结构。" },
  { words: ["oscillate", "vacillate"], distinction: "oscillate 可指物理摆动或观点来回变化；vacillate 专指犹豫不决。", hook: "钟摆 oscillates；拿不定主意时 vacillate。" },
  { words: ["plaintive", "plaintiff"], distinction: "plaintive 是声音哀伤的；plaintiff 是法庭上的原告。", hook: "plaintive cry；plaintiff files a claim。" },
  { words: ["specious", "spurious"], distinction: "specious 是表面有理但实际错误；spurious 是虚假、伪造或来源不正。", hook: "specious argument 看似合理；spurious evidence 根本不真。" },
  { words: ["discreet", "discrete"], distinction: "discreet 是谨慎低调；discrete 是分离、互不相连。", hook: "discrete 的两个 e 被分开；discreet 的 ee 靠在一起守秘密。" },
  { words: ["censure", "censor"], distinction: "censure 是公开谴责；censor 是审查或删改内容。", hook: "censure expresses blame；censor removes content。" },
  { words: ["anecdote", "antidote"], distinction: "anecdote 是轶事；antidote 是解毒剂或补救方法。", hook: "anecdote tells a story；antidote treats a poison。" },
  { words: ["callous", "callow"], distinction: "callous 是冷酷无情；callow 是年轻且缺乏经验。", hook: "callous heart；callow youth。" },
  { words: ["commend", "commence"], distinction: "commend 是称赞、推荐；commence 是开始。", hook: "commend a student；commence a ceremony。" },
  { words: ["vivacious", "voracious"], distinction: "vivacious 是活泼有生气；voracious 是贪吃或极度渴求。", hook: "vivacious vitality；voracious appetite。" }
];
